services:
  rustdesk-api-server-pro:
    container_name: rustdesk-api-server-pro
    image: ghcr.io/lantongxue/rustdesk-api-server-pro:latest
    environment:
      - "ADMIN_USER=admin" # optional
      - "ADMIN_PASS=Moomkenwe09" # optional
    ports:
      - "8099:8080" # External:Internal
    volumes:
      - ./server.yaml:/app/server.yaml
    # network_mode: host
    restart: unless-stopped
